def get_translate(name):
    if name in TRANSLATES:
        return TRANSLATES[name]
    return name


TRANSLATES = {
    "bank_account": "Numero de cuenta",
    "bank_card_number": "Numero de tarjeta",
    "bank_id": "Banco",
    "birth_date": "Fecha de cumpleaños",
    "blood_type": "Tipo de sangre",
    "city": "Ciudad",
    "city_id": "Ciudad de nacimiento",
    "clients_trade_name_id": "Cliete/punto",
    "created_date": "Fecha de registro",
    "created_by": "Creado por",
    "credit_number": "# credito",
    "credit_value": "Valor del credito",
    "cuip": "CUIP",
    "curp": "CURP",
    "date_start": "Fecha de inicio",
    "date_end": "Fecha de finalizacion",
    "employer_registration_id": "Registro patronal",
    "external_number": "Numero exterior",
    "gender": "Genero",
    "id": "ID",
    "internal_number": "Numero interior",
    "last_name": "Apellido paterno",
    "location": "Ciudad de trabajo",
    "leave_desc": "Descripcion de la baja",
    "middle_name": "Apellido materno",
    "name": "Nombre",
    "nss": "NSS",
    "observations": "observaciones",
    "payroll_id": "Tipo de nomina",
    "photo": "URL DE LA FOTO",
    "position_id": "Puesto",
    "postal_code": "Codigo Postal",
    "punto": "Punto",
    "rfc": "RFC",
    "removed_by": "Dado de baja por",
    "registro_patronal": "Registro Patronal",
    "salary": "Salario",
    "sdi_imss": "sdi imss",
    "services_id": "Servico",
    "status": "Estatus",
    "street": "Calle",
    "suburb": "Colonia",
    "supervisor": "Supervidor",
    "telephone": "Telefono",
    "type_credit_infonavit": "Tipo de credito infonavit",
    "type_overtime_id": "Tipo de tiempo extra",
    "authorized_employees":"Empleados autorizados",
    "trade_name":"Nombre comercial / punto",
    "business_name":"Cliente",
    "turns":"Turnos",
    "authorized_salary":"Salario autorizado",
    "infonavit":"Infonavit a descontar",
    "bonus":"Aguinaldo",
    "purchase_order":"Orden de compra",
    "weekly_bonus":"Bono Semanal",
    "day_salary":"Salario Diario",
    "total_pay":"Total a pagar",
    "biweekly_bonus":"Bono Quincenal",
    "event_bonus":"Bono Evento",
    "debts":"Adeudos",
    "credit":"Creditos",
    "amount_extra_time":"Cant. tiempo extra",
    "front":"frente",
    "right":"costado derecho",
    "left": "costado izquierdo",
    "back":"detras",
    "back_seats":"asientos traseros",
    "front_seats":"asientos delanteros",
    "tab":"tablero",
    "motor":"motor",
    "trunk":"cajuela",
    "tools":"herramientas"
}